### PR TITLE
list of assemblies -> hashset of strings

### PR DESCRIPTION
**Pull request by 304NotModified**
no need for assembly

### CODE REVIEW

**Comment by ilya-g** [comment]
I don't see benefits in using assembly names instead of assemblies because of the following reasons:

* assemblies are compared by reference, whereas strings are compared by value: in general case it takes longer to compare two strings than compare two references.
* it may take time (though only one time) to generate assemly name,
* if you provide a method `AddHiddenAssembly`, which takes a string with assembly name, you have to deal somehow with assembly name normalization, since the name of an assembly can have different (though same meaning) forms.

**Comment by 304NotModified** [comment]
@ilya-g there are a lot of benefits. But first:

>assemblies are compared by reference
I think they are compared with the `.equals`. (with `==`) This isn't cheap. We don't now any performance facts about this. 
> whereas strings are compared by value
I don't compare strings. I compare hashes of a string (`hashTable`)

Performance is always a memory versus CPU. So we cannot really say the performance is better or worse. 

The benefits:
- The properties are `static` so the object stays in memory. The `Assembly` object isn't small. So this is far more better for the memory usage.
- We are now more flexible. Why should I pas an `Assembly` type, if only a string is needed? Now both are OK.
- The strings make it easy to make an `HashTable` which scales (CPU) far more better then the bad-scaling `.Where`. (of course this is also possible with `Assembly`, but generating the hashcode of an `Assembly` is far more complex. (and unneeded)
- We don't use anything of the `Assembly`, so why keeping them in memory? This is also pollutes the code. 

The real CPU benefit is here that the `.Where` is replaced by a 'HashTable'. Also it's far more easier for an user to use this (case insensitive, no `gettype` needed)

**Comment by ilya-g** [comment]
> I think they are compared with the .equals. (with ==) This isn't cheap. We don't know any performance facts about this.
> but generating the hashcode of an Assembly is far more complex.

Take a look at how `Equals` and `GetHashCode` are implemented in the `Assembly` (and its inheritor, that we deal with in runtime, `RuntimeAssembly`). They all inherit their actual implementation from the `Object`, so `Equals` is just a comparison of two references, and `GetHashCode` is same as `object.GetHashCode`.

> We are now more flexible. Why should I pas an Assembly type, if only a string is needed? Now both are OK.

Ok, but now you should be flexible enough to treat these two assembly names as equivalent:

`````C#
"NLog, Version=3.2.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c"
@"NLog,Version=3.2,Culture=neutral,
PublicKeyToken=5120e14c03d0593c"
`````

> We don't use anything of the Assembly, so why keeping them in memory?

Once an assembly is loaded in appDomain it doesn't get unloaded until the entire appDomain is unloaded. So it's no matter whether you keep a reference to the assembly or don't, it is still in memory.

> The real CPU benefit is here that the .Where is replaced by a 'HashTable'.

You are right, that `HashSet.Contains` works faster than `List.Contains`, when there are more than 1–2 elements in a list.

**Comment by 304NotModified** [comment]
>Once an assembly is loaded in appDomain it doesn't get unloaded until the entire appDomain is unloaded. So it's no matter whether you keep a reference to the assembly or don't, it is still in memory.

That's is really good point. 

> GetHashCode is same as object.GetHashCode.

I quote: ", do not use the default implementation of this method as a unique object identifier for hashing purpose"  from [Object.GetHashCode Method](https://msdn.microsoft.com/en-us/library/system.object.gethashcode.aspx)

**Comment by ilya-g** [comment]
> do not use the default implementation of this method as a unique object identifier for hashing purpose

This quote should not be taken out of context. It implies, first, that hash code values are not unique, and not to be used as an object unique identifier, because different objects can have the same hash code value.
Second, you should not persist the returned value across different appdomains: for example, if you want to calculate persistent hash of some object, do not include in that hash neither its `GetHashCode` value nor `GetHashCode` value of any of its properties/fields.
The full list of cautions what should not be done with the `GetHashCode` values is shown below in that article.

It also states that "A hash code is intended for efficient insertion and lookup in collections that are based on a hash table.". Then it would be nonsense if the default implementation of `GetHashCode` could not be used for such purpose.

Also take a look at [`RuntimeHelpers.GetHashCode`](https://msdn.microsoft.com/en-us/library/11tbk3h9.aspx) documentation, which is used as the default implementation of `GetHashCode` for reference type objects, that do not override it.

**Comment by 304NotModified** [comment]
OK, thanks.

**Pull request closed without merging**
