### PR TITLE
Sync back

### PR DESCRIPTION
**Pull request by 304NotModified**

### CODE REVIEW

**Comment by ilya-g** [comment]
@304NotModified, did you know that you can synchonize the `master` branch in your repository with the corresponding `master` branch in NLog without creating a pull request from NLog repository?

Just pull the changes from NLog to your local disk clone and then push them to your github repo.

**Comment by 304NotModified** [comment]
@ilya-g But this gives me extra credits? (contribution points)? 

LOL

But serious, I didn't now. I use GitHub for Windows because it works well with GitHub. I don't now what `git` command I should use now to fix this.

And the network graph don't look bad? What could be better there?

**Comment by ilya-g** [comment]
Here is the instruction for command line how to sync your fork with the repo: https://help.github.com/articles/fork-a-repo/#keep-your-fork-synced.

This blue part of graph illustrates a clean working process for developing a feature: 


1. create a new branch from the latest master;
1. push one or more commits to that branch;
1. have it merged back to master;
1. delete the branch, because now it is finished.

See also [an article](https://help.github.com/articles/github-flow-in-the-browser/) about this workflow

**Comment by 304NotModified** [comment]
Well I'm doing that. 

But my master branch was behind, so I have to 'sync back' that. Not sure how to do that otherwise then a PR.

**Comment by ilya-g** [comment]
You're welcome. Would be glad to answer to any questions if you had ones.

**Pull request merged**
